## Animation Config
Animation_CONF_default:
  options:
    loop:

## AI Config
AI_CONF_default1:
  num_generation: 3
  num_threads: 1
  provider: openrouter
  rag:
    enabled: false
  ocr:
    deepseek_refine: false
  textgroup:
    temperature: 0.0
  animation:
    temperature: 0.0

## Rendering COnfig
Render_CONF_default1:
  max_video_duration: 30
  num_threads: 1
